<?php
if (realpath($_SERVER['SCRIPT_FILENAME'] ?? '') === __FILE__) {
    http_response_code(404);
    exit;
}

// 1 Administrador, 2 Psicóloga, 3 Docente, 4 Director.
// Las rutas no declaradas se rechazan. Toda petición POST exige CSRF.
return [
    'index.php' => ['roles' => [1, 2], 'metodos' => ['GET', 'HEAD']],
    'usuarios/listar.php' => ['roles' => [1], 'metodos' => ['GET', 'HEAD']],
    'usuarios/ver.php' => ['roles' => [1], 'metodos' => ['GET', 'HEAD']],
    'usuarios/registrar.php' => ['roles' => [1], 'metodos' => ['GET', 'HEAD']],
    'usuarios/editar.php' => ['roles' => [1], 'metodos' => ['GET', 'HEAD']],
    'usuarios/guardar.php' => ['roles' => [1], 'metodos' => ['POST']],
    'usuarios/actualizar.php' => ['roles' => [1], 'metodos' => ['POST']],
    'usuarios/cambiar_estado.php' => ['roles' => [1], 'metodos' => ['POST']],
    'docentes/listar.php' => ['roles' => [1], 'metodos' => ['GET', 'HEAD']],
    'docentes/ver.php' => ['roles' => [1], 'metodos' => ['GET', 'HEAD']],
    'docentes/registrar.php' => ['roles' => [1], 'metodos' => ['GET', 'HEAD']],
    'docentes/editar.php' => ['roles' => [1], 'metodos' => ['GET', 'HEAD']],
    'docentes/guardar.php' => ['roles' => [1], 'metodos' => ['POST']],
    'docentes/actualizar.php' => ['roles' => [1], 'metodos' => ['POST']],
    'estudiantes/listar.php' => ['roles' => [1, 2], 'metodos' => ['GET', 'HEAD', 'POST']],
    'estudiantes/registrar.php' => ['roles' => [1, 2], 'metodos' => ['GET', 'HEAD']],
    'estudiantes/editar.php' => ['roles' => [1, 2], 'metodos' => ['GET', 'HEAD']],
    'estudiantes/guardar.php' => ['roles' => [1, 2], 'metodos' => ['POST']],
    'estudiantes/actualizar.php' => ['roles' => [1, 2], 'metodos' => ['POST']],
    'estudiantes/eliminar.php' => ['roles' => [1, 2], 'metodos' => ['POST']],
    'estudiantes/importar.php' => ['roles' => [1, 2], 'metodos' => ['POST']],
    'derivaciones/listar.php' => ['roles' => [1, 2, 3], 'metodos' => ['GET', 'HEAD']],
    'derivaciones/ver.php' => ['roles' => [1, 2, 3], 'metodos' => ['GET', 'HEAD']],
    'derivaciones/mis_derivaciones.php' => ['roles' => [3], 'metodos' => ['GET', 'HEAD']],
    'derivaciones/registrar.php' => ['roles' => [1, 3], 'metodos' => ['GET', 'HEAD']],
    'derivaciones/editar.php' => ['roles' => [1, 3], 'metodos' => ['GET', 'HEAD']],
    'derivaciones/guardar.php' => ['roles' => [1, 3], 'metodos' => ['POST']],
    'derivaciones/actualizar.php' => ['roles' => [1, 3], 'metodos' => ['POST']],
    'derivaciones/eliminar.php' => ['roles' => [3], 'metodos' => ['POST']],
    'derivaciones/cambiar_estado.php' => ['roles' => [1, 2], 'metodos' => ['POST']],
    'seguimientos/registrar.php' => ['roles' => [1, 2], 'metodos' => ['GET', 'HEAD']],
    'seguimientos/guardar.php' => ['roles' => [1, 2], 'metodos' => ['POST']],
    'seguimientos/ver.php' => ['roles' => [1, 2], 'metodos' => ['GET', 'HEAD']],
    'citas/listar.php' => ['roles' => [1, 2], 'metodos' => ['GET', 'HEAD']],
    'citas/registrar.php' => ['roles' => [1, 2], 'metodos' => ['GET', 'HEAD']],
    'citas/editar.php' => ['roles' => [1, 2], 'metodos' => ['GET', 'HEAD']],
    'citas/procesar_registrar.php' => ['roles' => [1, 2], 'metodos' => ['POST']],
    'citas/procesar_editar.php' => ['roles' => [1, 2], 'metodos' => ['POST']],
    'citas/cancelar.php' => ['roles' => [1, 2], 'metodos' => ['POST']],
    'historias_clinicas/listar.php' => ['roles' => [1, 2], 'metodos' => ['GET', 'HEAD']],
    'historias_clinicas/ver.php' => ['roles' => [1, 2], 'metodos' => ['GET', 'HEAD']],
    'historias_clinicas/registrar.php' => ['roles' => [1, 2], 'metodos' => ['GET', 'HEAD']],
    'historias_clinicas/editar.php' => ['roles' => [1, 2], 'metodos' => ['GET', 'HEAD']],
    'historias_clinicas/guardar.php' => ['roles' => [1, 2], 'metodos' => ['POST']],
    'historias_clinicas/actualizar.php' => ['roles' => [1, 2], 'metodos' => ['POST']],
    'historias_clinicas/ajax_derivaciones.php' => ['roles' => [1, 2], 'metodos' => ['GET', 'HEAD'], 'formato' => 'json'],
    'informes/listar.php' => ['roles' => [1, 2, 4], 'metodos' => ['GET', 'HEAD']],
    'informes/ver.php' => ['roles' => [1, 2, 4], 'metodos' => ['GET', 'HEAD']],
    'informes/registrar.php' => ['roles' => [1, 2], 'metodos' => ['GET', 'HEAD']],
    'informes/editar.php' => ['roles' => [1, 2], 'metodos' => ['GET', 'HEAD']],
    'informes/guardar.php' => ['roles' => [1, 2], 'metodos' => ['POST']],
    'informes/actualizar.php' => ['roles' => [1, 2], 'metodos' => ['POST']],
];
